name: Build and Deploy

on:
  schedule:
    - cron: '13 6 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Usage'
        default: '[test]'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Build 🔧
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy 🚀
        run: |
          make gitEnv
          make install
          make run
          make deploy